language: python

services:
- docker

python:
- 3.5
- 3.6
- nightly

matrix:
  allow_failures:
  - python: nightly

install:
# - pip install --upgrade setuptools
- pip install wheel
- pip install -r requirements-dev.txt
- pip install codecov

script:
- make cov
- python setup.py check -rm
- if python -c "import sys; sys.exit(sys.version_info < (3,5))"; then
      python setup.py check -s;
  fi

sudo: false
